PUSHD .
python "darts-voice.py" ^
-CON "127.0.0.1:8079" ^
-MP "C:\\Users\\Luca\\Desktop\\Programme\\darts-hub\\darts-voice-vosk-models\\vosk-model-small-de-0.15" ^
-L "0" ^
-KNG "nächstes spiel" ^
-KN "weiter" ^
-KU "zurück" ^
-KBC "verbannen" ^
-KCC "wechseln" ^
-KSB "brett starten" ^
-KSPB "brett stoppen" ^
-KRB "brett zurücksetzen" ^
-KCB "brett kalibrieren" ^
-KFD "erster" "erste" "erstens" ^
-KSD "zweiter" "zweite" "zweitens" ^
-KTD "dritter" "dritte" "drittens" "britta" ^
-KS "einfach" ^
-KD "doppel" "doppelt" ^
-KT "dreifach" ^
-KZERO "null" "vorbei" ^
-KONE "eins" ^
-KTWO "zwei" ^
-KTHREE "drei" ^
-KFOUR "vier" ^
-KFIVE "fünf" ^
-KSIX "sechs" ^
-KSEVEN "sieben" ^
-KEIGHT "acht" ^
-KNINE "neun" ^
-KTEN "zehn" ^
-KELEVEN "elf" ^
-KTWELVE "zwölf" ^
-KTHIRTEEN "dreizehn" ^
-KFOURTEEN "vierzehn" ^
-KFIFTEEN "fünfzehn" ^
-KSIXTEEN "sechzehn" ^
-KSEVENTEEN "siebzehn" ^
-KEIGHTEEN "achtzehn" "option" ^
-KNINETEEN "neunzehn" ^
-KTWENTY "zwanzig" ^
-KTWENTYFIVE "fünfundzwanzig" ^
-KFIFTY "fünfzig" ^
-DEB "1"